name: rvc-tts-webui
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - edge-tts=6.1.7
  - fairseq=0.12.2
  - faiss-cpu=1.7.4
  - gradio=3.38.0
  - librosa=0.9.1
  - numpy=1.23.5
  - praat-parselmouth=0.4.3
  - pyworld=0.3.4
  - torchcrepe=0.0.20
  - fastapi=0.103.1
  - uvicorn=0.23.2
  - omegaconf=2.0.5
  - hydra-core=1.0.7

